/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ClienteController;
import controller.ProdutoController;
import controller.VendaController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ClienteModel;
import model.ProdutoModel;
import util.Utilidades;
import util.Validador;

/**
 *
 * @author Sakemi
 */
public class TelaPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipalView() {
        initComponents();
        setLocationRelativeTo(null);
        loadTableClientes();
        loadTableProdutos();
        loadTableVendas();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pnlVendas = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        btnBuscarVenda = new javax.swing.JButton();
        btnVisualizarV = new javax.swing.JButton();
        txtPeriodo1 = new javax.swing.JTextField();
        txtCPFbusca = new javax.swing.JTextField();
        lblPeriodo = new javax.swing.JLabel();
        lblIDCbusca = new javax.swing.JLabel();
        txtIDVenda = new javax.swing.JTextField();
        lblIDV = new javax.swing.JLabel();
        txtPeriodo2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblVendas = new javax.swing.JTable();
        btnNovaVenda = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblValorTotal = new javax.swing.JLabel();
        btnAtualizarVenda = new javax.swing.JButton();
        pnlProduto = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        txtNomeProduto = new javax.swing.JTextField();
        lblNomeProduto = new javax.swing.JLabel();
        txtIDProduto = new javax.swing.JTextField();
        lblIDProduto = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        btnBuscarProduto = new javax.swing.JButton();
        btnVisualizarProduto = new javax.swing.JButton();
        btnNovoProduto = new javax.swing.JButton();
        btnExcluirProduto = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProduto = new javax.swing.JTable();
        AtualizarProduto = new javax.swing.JButton();
        pnlClientes = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        btnBuscarCliente = new javax.swing.JButton();
        btnVisualizarCliente = new javax.swing.JButton();
        btnNovoCliente = new javax.swing.JButton();
        btnExcluirCliente = new javax.swing.JButton();
        txtNomeCliente = new javax.swing.JTextField();
        lblNomeC = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        lblIDC = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();
        AtualizarC = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jTabbedPane2.addTab("tab1", jTabbedPane3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 257, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlVendas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Relatório de Vendas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        btnBuscarVenda.setText("Buscar");
        btnBuscarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVendaActionPerformed(evt);
            }
        });

        btnVisualizarV.setText("Visualizar");
        btnVisualizarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnVisualizarV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(btnBuscarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscarVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVisualizarV)
                .addContainerGap())
        );

        txtPeriodo1.setPreferredSize(new java.awt.Dimension(140, 25));

        txtCPFbusca.setPreferredSize(new java.awt.Dimension(140, 25));

        lblPeriodo.setText("Período:");

        lblIDCbusca.setText("CPF Cliente:");

        txtIDVenda.setPreferredSize(new java.awt.Dimension(140, 25));

        lblIDV.setText("ID Venda:");

        txtPeriodo2.setPreferredSize(new java.awt.Dimension(140, 25));

        jLabel1.setText("-");

        tblVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Venda", "CPF Cliente", "Data", "Valor Total"
            }
        ));
        jScrollPane4.setViewportView(tblVendas);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIDV)
                    .addComponent(txtIDVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIDCbusca)
                    .addComponent(txtCPFbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPeriodo)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(txtPeriodo1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPeriodo2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane4)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(lblIDV)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIDVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(lblIDCbusca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCPFbusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(lblPeriodo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPeriodo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPeriodo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)))))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnNovaVenda.setText("Nova Venda");
        btnNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovaVendaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Total: R$ ");

        lblValorTotal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblValorTotal.setText("xx.xx");

        btnAtualizarVenda.setText("Atualizar");
        btnAtualizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlVendasLayout = new javax.swing.GroupLayout(pnlVendas);
        pnlVendas.setLayout(pnlVendasLayout);
        pnlVendasLayout.setHorizontalGroup(
            pnlVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlVendasLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValorTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAtualizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNovaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlVendasLayout.setVerticalGroup(
            pnlVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovaVenda)
                    .addComponent(jLabel2)
                    .addComponent(lblValorTotal)
                    .addComponent(btnAtualizarVenda))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Vendas", pnlVendas);

        pnlProduto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Produtos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        txtNomeProduto.setPreferredSize(new java.awt.Dimension(140, 25));

        lblNomeProduto.setText("Nome:");

        txtIDProduto.setPreferredSize(new java.awt.Dimension(140, 25));

        lblIDProduto.setText("ID do Produto:");

        btnBuscarProduto.setText("Buscar");
        btnBuscarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProdutoActionPerformed(evt);
            }
        });

        btnVisualizarProduto.setText("Visualizar");
        btnVisualizarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarProdutoActionPerformed(evt);
            }
        });

        btnNovoProduto.setText("Novo");
        btnNovoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoProdutoActionPerformed(evt);
            }
        });

        btnExcluirProduto.setText("Excluir");
        btnExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(btnBuscarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNovoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(btnVisualizarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarProduto)
                    .addComponent(btnNovoProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisualizarProduto)
                    .addComponent(btnExcluirProduto))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIDProduto)
                    .addComponent(txtIDProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeProduto)
                    .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblIDProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lblNomeProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 88, Short.MAX_VALUE)
        );

        tblProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Marca", "Estoque", "Valor"
            }
        ));
        jScrollPane2.setViewportView(tblProduto);

        AtualizarProduto.setText("Atualizar");
        AtualizarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlProdutoLayout = new javax.swing.GroupLayout(pnlProduto);
        pnlProduto.setLayout(pnlProdutoLayout);
        pnlProdutoLayout.setHorizontalGroup(
            pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProdutoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AtualizarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlProdutoLayout.setVerticalGroup(
            pnlProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AtualizarProduto)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Produtos", pnlProduto);

        pnlClientes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clientes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        btnVisualizarCliente.setText("Visualizar");
        btnVisualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarClienteActionPerformed(evt);
            }
        });

        btnNovoCliente.setText("Novo");
        btnNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoClienteActionPerformed(evt);
            }
        });

        btnExcluirCliente.setText("Excluir");
        btnExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(btnVisualizarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscarCliente)
                    .addComponent(btnNovoCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisualizarCliente)
                    .addComponent(btnExcluirCliente))
                .addGap(15, 15, 15))
        );

        txtNomeCliente.setPreferredSize(new java.awt.Dimension(140, 25));

        lblNomeC.setText("Nome:");

        txtCPF.setPreferredSize(new java.awt.Dimension(140, 25));

        lblIDC.setText("CPF");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIDC)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeC)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(lblIDC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(lblNomeC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, Short.MAX_VALUE)
                .addContainerGap())
        );

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "CPF", "E-mail", "Celular"
            }
        ));
        jScrollPane3.setViewportView(tblCliente);

        AtualizarC.setText("Atualizar");
        AtualizarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtualizarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlClientesLayout = new javax.swing.GroupLayout(pnlClientes);
        pnlClientes.setLayout(pnlClientesLayout);
        pnlClientesLayout.setHorizontalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlClientesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(AtualizarC, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlClientesLayout.setVerticalGroup(
            pnlClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AtualizarC)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Clientes", pnlClientes);

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 48)); // NOI18N
        jLabel3.setText("TableTop");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Webp.net-resizeimage.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(182, 182, 182))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarClienteActionPerformed
        if (tblCliente.getRowCount() > 0) {
            int linha = tblCliente.getSelectedRow();

            if (linha >= 0) {

                int id = Integer.parseInt(tblCliente.getModel().getValueAt(linha, 0).toString());
                ClienteModel c = ClienteController.visualizar(id);
                new CadastroClienteView(this, c).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um cliente para visualizar!");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Não há cliente para visualizar!");
        }
    }//GEN-LAST:event_btnVisualizarClienteActionPerformed

    private void btnNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoClienteActionPerformed
        new CadastroClienteView(this).setVisible(true);
    }//GEN-LAST:event_btnNovoClienteActionPerformed

    private void btnExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirClienteActionPerformed
        if (tblCliente.getRowCount() > 0) {
            int linha = tblCliente.getSelectedRow();

            if (linha >= 0) {
                int IDcliente = Integer.parseInt(tblCliente.getModel().getValueAt(linha, 0).toString());

                if (ClienteController.excluir(IDcliente)) {
                    loadTableClientes();
                    JOptionPane.showMessageDialog(this, "Cliente excluido da base de dados!");
                } else {
                    JOptionPane.showMessageDialog(this, "Falha ao excluir o cliente!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Selecione o cliente a ser excluído!");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Não há clientes para excluir!");
        }
    }//GEN-LAST:event_btnExcluirClienteActionPerformed

    private void btnVisualizarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarProdutoActionPerformed

        if (tblProduto.getRowCount() > 0) {
            int linha = tblProduto.getSelectedRow();
            if (linha >= 0) {
                ProdutoModel p = ProdutoController.visualizar(linha, tblProduto.getModel());
                new CadastroProdutoView(this, p).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um produto para visualizar!");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Não há produtos para visualizar!");
        }

    }//GEN-LAST:event_btnVisualizarProdutoActionPerformed

    private void btnNovoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoProdutoActionPerformed
        CadastroProdutoView cp = new CadastroProdutoView(this);
        cp.setVisible(true);
    }//GEN-LAST:event_btnNovoProdutoActionPerformed

    private void btnExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdutoActionPerformed
        if (tblProduto.getRowCount() > 0) {
            int linha = tblProduto.getSelectedRow();

            if (linha >= 0) {
                int IDproduto = Integer.parseInt(tblProduto.getModel().getValueAt(linha, 0).toString());

                if (ProdutoController.excluir(IDproduto)) {
                    loadTableProdutos();
                    JOptionPane.showMessageDialog(this, "Produto excluido da base de dados!");
                } else {
                    JOptionPane.showMessageDialog(this, "Falha ao excluir o produto!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Selecione o produto a ser excluído!");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Não há produtos para excluir!");
        }
    }//GEN-LAST:event_btnExcluirProdutoActionPerformed

    private void AtualizarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarProdutoActionPerformed
        loadTableProdutos();
    }//GEN-LAST:event_AtualizarProdutoActionPerformed

    private void AtualizarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizarCActionPerformed
        loadTableClientes();
    }//GEN-LAST:event_AtualizarCActionPerformed

    private void btnBuscarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProdutoActionPerformed
        int id;
        String nome;
        if (tblProduto.getRowCount() > 0) {

            if (validarBuscaProduto()) {
                if (!txtIDProduto.getText().equals("")) {
                    id = Integer.parseInt(txtIDProduto.getText());

                    buscaProduto(id);
                } else {
                    nome = txtNomeProduto.getText().toLowerCase();

                    buscaProduto(nome);
                }

            }
        } else {
            JOptionPane.showMessageDialog(this, "Não há produtos para buscar!");
        }
    }//GEN-LAST:event_btnBuscarProdutoActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        long cpf;
        String nome;
        if (tblProduto.getRowCount() > 0) {

            if (validarBuscaCliente()) {
                if (!txtCPF.getText().equals("")) {
                    cpf = Long.parseLong(txtCPF.getText());
                    buscaCliente(cpf);
                } else {
                    nome = txtNomeCliente.getText().toLowerCase();

                    buscaCliente(nome);
                }

            }
        } else {
            JOptionPane.showMessageDialog(this, "Não há clientes para buscar!");
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovaVendaActionPerformed
        VendaView v = new VendaView(this);
        v.setVisible(true);
    }//GEN-LAST:event_btnNovaVendaActionPerformed

    private void btnAtualizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarVendaActionPerformed
        loadTableVendas();
        getTotalVendas();
    }//GEN-LAST:event_btnAtualizarVendaActionPerformed

    private void btnVisualizarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarVActionPerformed
        int linha;

        if (tblVendas.getRowCount() > 0) {
            linha = tblVendas.getSelectedRow();
            if (linha >= 0) {
                int id = Integer.parseInt(tblVendas.getModel().getValueAt(linha, 0).toString());

                new RelatórioView(id).setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Selecione uma venda para visualizar!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Não há vendas para visualizar!");
        }
        getTotalVendas();

    }//GEN-LAST:event_btnVisualizarVActionPerformed

    private void btnBuscarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVendaActionPerformed

        if (validarBuscaVendas()) {
            if (!txtIDVenda.getText().equalsIgnoreCase("")) {
                buscaVendas(Integer.parseInt(txtIDVenda.getText()));
            } else if (!txtCPFbusca.getText().equalsIgnoreCase("")) {
                buscaVendas(txtCPFbusca.getText());
            } else {
                buscaVendas(txtPeriodo1.getText(), txtPeriodo2.getText());
            }
        }

        getTotalVendas();

    }//GEN-LAST:event_btnBuscarVendaActionPerformed

    private boolean validarBuscaVendas() {
        boolean idPreenchido = !txtIDVenda.getText().equalsIgnoreCase(""),
                cpfPreenchido = !txtCPFbusca.getText().equalsIgnoreCase(""),
                inicioPeriodo = !txtPeriodo1.getText().replace("/", "").equalsIgnoreCase(""),
                fimPeriodo = !txtPeriodo2.getText().replace("/", "").equalsIgnoreCase("");

        if (idPreenchido || cpfPreenchido || (inicioPeriodo && fimPeriodo)) {
            if (idPreenchido && !Validador.validarInt(txtIDVenda.getText())) {
                JOptionPane.showMessageDialog(this, "ID de venda Inválido!");
                return false;
            }
            if (cpfPreenchido && !Validador.validarCPF(txtCPFbusca.getText())) {
                JOptionPane.showMessageDialog(this, "CPF Inválido!");
                return false;
            }
            if (inicioPeriodo && fimPeriodo && !Validador.validarData(txtPeriodo1.getText()) && !Validador.validarData(txtPeriodo2.getText())) {
                JOptionPane.showMessageDialog(this, "Período Inválido!");
                return false;
            }
            if (inicioPeriodo && fimPeriodo && Utilidades.dataPosterior(txtPeriodo1.getText().split("/"), txtPeriodo2.getText().split("/"))) {
                JOptionPane.showMessageDialog(this, "Período Inválido!");
                return false;
            }
            return true;
        } else {
            JOptionPane.showMessageDialog(this, "Informe o ID da venda, CPF do cliente ou o período a ser pesquisado!");
            return false;
        }
    }

    private boolean validarBuscaProduto() {
        boolean idPreenchido = !txtIDProduto.getText().equalsIgnoreCase("");
        boolean nomePreenchido = !txtNomeProduto.getText().equalsIgnoreCase("");

        if (!idPreenchido && !nomePreenchido) {
            JOptionPane.showMessageDialog(this, "Informe o ID ou o Nome do produto!");
            return false;

        } else if (idPreenchido && !Validador.validarInt(txtIDProduto.getText())) {
            JOptionPane.showMessageDialog(this, "ID inválido!");
            return false;
        }

        return true;
    }

    private boolean validarBuscaCliente() {
        boolean idPreenchido = !txtCPF.getText().equalsIgnoreCase("");
        boolean nomePreenchido = !txtNomeCliente.getText().equalsIgnoreCase("");

        if (!idPreenchido && !nomePreenchido) {
            JOptionPane.showMessageDialog(this, "Informe o ID ou o Nome do cliente!");
            return false;

        } else if (idPreenchido && !Validador.validarCPF(txtCPF.getText())) {
            JOptionPane.showMessageDialog(this, "CPF inválido!");
            return false;
        }

        return true;
    }

    public void loadTableProdutos() {

        ArrayList<String[]> linhasProdutos = ProdutoController.getProdutos();

        DefaultTableModel tmProdutos = new DefaultTableModel();
        tmProdutos.addColumn("ID");
        tmProdutos.addColumn("Nome");
        tmProdutos.addColumn("Marca");
        tmProdutos.addColumn("Fornecedor");
        tmProdutos.addColumn("Estoque");
        tmProdutos.addColumn("Valor");
        tmProdutos.addColumn("Descrição");
        tblProduto.setModel(tmProdutos);

        tblProduto.removeColumn(tblProduto.getColumnModel().getColumn(3));
        tblProduto.removeColumn(tblProduto.getColumnModel().getColumn(5));

        for (String[] p : linhasProdutos) {
            tmProdutos.addRow(p);
        }

    }

    public void loadTableClientes() {

        ArrayList<ClienteModel> clientes = ClienteController.loadClientes();

        DefaultTableModel tmClientes = new DefaultTableModel();
        tmClientes.addColumn("ID");
        tmClientes.addColumn("Nome");
        tmClientes.addColumn("CPF");
        tmClientes.addColumn("Email");
        tmClientes.addColumn("Celular");

        tblCliente.setModel(tmClientes);

        for (ClienteModel c : clientes) {
            tmClientes.addRow(c.toArray());
        }

    }

    public void loadTableVendas() { //alterar

        ArrayList<String[]> linhasVendas = VendaController.getVendas();

        DefaultTableModel tmVendas = new DefaultTableModel();
        tmVendas.addColumn("IDVenda");
        tmVendas.addColumn("CPF Cliente");
        tmVendas.addColumn("Data");
        tmVendas.addColumn("Valor Total");
        tblVendas.setModel(tmVendas);

        for (String[] v : linhasVendas) {
            tmVendas.addRow(v);
        }
        getTotalVendas();

    }

    public void getTotalVendas() {
        double total = 00.00;
        int linhas = tblVendas.getRowCount();
        for (int i = 0; i < linhas; i++) {
            double valor = Double.parseDouble(tblVendas.getModel().getValueAt(i, 3).toString());
            total += valor;
        }

        lblValorTotal.setText(String.format("%.2f", total));
    }

    public void buscaVendas(int id) {
        ArrayList<String[]> linhasVendas = VendaController.buscaVenda(id);
        DefaultTableModel tmVendas = new DefaultTableModel();
        tmVendas.addColumn("IDVenda");
        tmVendas.addColumn("CPF Cliente");
        tmVendas.addColumn("Data");
        tmVendas.addColumn("Valor Total");
        tblVendas.setModel(tmVendas);

        for (String[] v : linhasVendas) {
            tmVendas.addRow(v);
        }
    }

    public void buscaVendas(String dataInicio, String dataFim) {
        ArrayList<String[]> linhasVendas = VendaController.buscaVenda(dataInicio, dataFim);
        DefaultTableModel tmVendas = new DefaultTableModel();
        tmVendas.addColumn("IDVenda");
        tmVendas.addColumn("CPF Cliente");
        tmVendas.addColumn("Data");
        tmVendas.addColumn("Valor Total");
        tblVendas.setModel(tmVendas);

        for (String[] v : linhasVendas) {
            tmVendas.addRow(v);
        }
    }

    public void buscaVendas(String cpf) {
        ArrayList<String[]> linhasVendas = VendaController.buscaVenda(cpf);
        DefaultTableModel tmVendas = new DefaultTableModel();
        tmVendas.addColumn("IDVenda");
        tmVendas.addColumn("CPF Cliente");
        tmVendas.addColumn("Data");
        tmVendas.addColumn("Valor Total");
        tblVendas.setModel(tmVendas);

        for (String[] v : linhasVendas) {
            tmVendas.addRow(v);
        }
    }

    public void buscaProduto(String nome) {
        ArrayList<String[]> linhasProdutos = ProdutoController.buscaProduto(nome);

        if (!linhasProdutos.isEmpty()) {

            DefaultTableModel tmProdutos = new DefaultTableModel();
            tmProdutos.addColumn("ID");
            tmProdutos.addColumn("Nome");
            tmProdutos.addColumn("Marca");
            tmProdutos.addColumn("Fornecedor");
            tmProdutos.addColumn("Estoque");
            tmProdutos.addColumn("Valor");
            tmProdutos.addColumn("Descrição");

            for (String[] p : linhasProdutos) {
                tmProdutos.addRow(p);
            }

            tblProduto.setModel(tmProdutos);
            tblProduto.removeColumn(tblProduto.getColumnModel().getColumn(3));
            tblProduto.removeColumn(tblProduto.getColumnModel().getColumn(5));
        } else {
            JOptionPane.showMessageDialog(this, "Produto não encontrado!");
        }

    }

    public void buscaProduto(int id) {
        ArrayList<String[]> linhasProdutos = ProdutoController.buscaProduto(id);

        if (!linhasProdutos.isEmpty()) {

            DefaultTableModel tmProdutos = new DefaultTableModel();
            tmProdutos.addColumn("ID");
            tmProdutos.addColumn("Nome");
            tmProdutos.addColumn("Marca");
            tmProdutos.addColumn("Fornecedor");
            tmProdutos.addColumn("Quantidade");
            tmProdutos.addColumn("Valor");
            tmProdutos.addColumn("Descrição");

            for (String[] p : linhasProdutos) {
                tmProdutos.addRow(p);
            }

            tblProduto.setModel(tmProdutos);
            tblProduto.removeColumn(tblProduto.getColumnModel().getColumn(3));
            tblProduto.removeColumn(tblProduto.getColumnModel().getColumn(5));
        } else {
            JOptionPane.showMessageDialog(this, "Produto não encontrado!");
        }
    }

    public void buscaCliente(String nome) {
        ArrayList<ClienteModel> clientes = ClienteController.buscaCliente(nome);

        if (!clientes.isEmpty()) {

            DefaultTableModel tmClientes = new DefaultTableModel();
            tmClientes.addColumn("ID");
            tmClientes.addColumn("Nome");
            tmClientes.addColumn("CPF");
            tmClientes.addColumn("Email");
            tmClientes.addColumn("Celular");

            tblCliente.setModel(tmClientes);

            for (ClienteModel c : clientes) {
                tmClientes.addRow(c.toArray());
            }

        } else {
            JOptionPane.showMessageDialog(this, "Cliente não encontrado!");
        }

    }

    public void buscaCliente(long cpf) {
        ClienteModel c = ClienteController.buscaCliente(cpf);

        if (c != null) {

            DefaultTableModel tmClientes = new DefaultTableModel();
            tmClientes.addColumn("ID");
            tmClientes.addColumn("Nome");
            tmClientes.addColumn("CPF");
            tmClientes.addColumn("Email");
            tmClientes.addColumn("Celular");

            tmClientes.addRow(c.toArray());

            tblCliente.setModel(tmClientes);

        } else {
            JOptionPane.showMessageDialog(this, "Cliente não encontrado!");
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipalView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalView().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AtualizarC;
    private javax.swing.JButton AtualizarProduto;
    private javax.swing.JButton btnAtualizarVenda;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarProduto;
    private javax.swing.JButton btnBuscarVenda;
    private javax.swing.JButton btnExcluirCliente;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.JButton btnNovaVenda;
    private javax.swing.JButton btnNovoCliente;
    private javax.swing.JButton btnNovoProduto;
    private javax.swing.JButton btnVisualizarCliente;
    private javax.swing.JButton btnVisualizarProduto;
    private javax.swing.JButton btnVisualizarV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblIDC;
    private javax.swing.JLabel lblIDCbusca;
    private javax.swing.JLabel lblIDProduto;
    private javax.swing.JLabel lblIDV;
    private javax.swing.JLabel lblNomeC;
    private javax.swing.JLabel lblNomeProduto;
    private javax.swing.JLabel lblPeriodo;
    private javax.swing.JLabel lblValorTotal;
    private javax.swing.JPanel pnlClientes;
    private javax.swing.JPanel pnlProduto;
    private javax.swing.JPanel pnlVendas;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTable tblProduto;
    private javax.swing.JTable tblVendas;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCPFbusca;
    private javax.swing.JTextField txtIDProduto;
    private javax.swing.JTextField txtIDVenda;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNomeProduto;
    private javax.swing.JTextField txtPeriodo1;
    private javax.swing.JTextField txtPeriodo2;
    // End of variables declaration//GEN-END:variables
}
